version: "3.9"
services:

  dev: &dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    tmpfs: ["/app/tmp", "/app/log"]
    environment:
      RAILS_ENV: development
      ENV: development
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: garpar
      MYSQL_USER: garpar
      MYSQL_PASSWORD: garpar
      DATABASE_URL: mysql2://garpar:garpar@db:3306/garpar
      PORT: 3000
    depends_on:
      db: {"condition":"service_healthy"}
    command: ["bundle", "exec", "./validate-migrated.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    ports: 
      - 3000:3000
  
  test: &test
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    tmpfs: ["/app/tmp", "/app/log"]
    environment:
      RAILS_ENV: test
      ENV: test
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: garpar_test
      MYSQL_USER: garpar
      MYSQL_PASSWORD: garpar
      DATABASE_URL: mysql2://garpar:garpar@db:3306/garpar_test
      PORT: 3001
    depends_on:
      db: {"condition":"service_healthy"}
  
  db: &db
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    ports:
      - 3306:3306 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-e", "select 1"]
      interval: 1s
      timeout: 1s
      retries: 300